# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'droidsTEMPLATE.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1116, 703)
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(10, 140, 221, 151))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(10, 10, 181, 20))
        self.label.setObjectName("label")
        self.textEdit = QtWidgets.QTextEdit(self.frame)
        self.textEdit.setGeometry(QtCore.QRect(10, 40, 191, 75))
        self.textEdit.setObjectName("textEdit")
        self.label_14 = QtWidgets.QLabel(self.frame)
        self.label_14.setGeometry(QtCore.QRect(10, 120, 191, 16))
        self.label_14.setObjectName("label_14")
        self.frame_2 = QtWidgets.QFrame(Dialog)
        self.frame_2.setGeometry(QtCore.QRect(10, 300, 221, 161))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.textEdit_2 = QtWidgets.QTextEdit(self.frame_2)
        self.textEdit_2.setGeometry(QtCore.QRect(10, 50, 191, 75))
        self.textEdit_2.setObjectName("textEdit_2")
        self.label_15 = QtWidgets.QLabel(self.frame_2)
        self.label_15.setGeometry(QtCore.QRect(10, 130, 201, 16))
        self.label_15.setObjectName("label_15")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setGeometry(QtCore.QRect(10, 20, 201, 20))
        self.label_2.setObjectName("label_2")
        self.frame_3 = QtWidgets.QFrame(Dialog)
        self.frame_3.setGeometry(QtCore.QRect(240, 100, 311, 381))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.lineEdit = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit.setGeometry(QtCore.QRect(20, 30, 113, 28))
        self.lineEdit.setObjectName("lineEdit")
        self.label_5 = QtWidgets.QLabel(self.frame_3)
        self.label_5.setGeometry(QtCore.QRect(20, 10, 261, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.frame_3)
        self.label_6.setGeometry(QtCore.QRect(20, 60, 271, 16))
        self.label_6.setObjectName("label_6")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_2.setGeometry(QtCore.QRect(20, 80, 113, 28))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_3.setGeometry(QtCore.QRect(20, 130, 113, 28))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_8 = QtWidgets.QLabel(self.frame_3)
        self.label_8.setGeometry(QtCore.QRect(20, 110, 271, 21))
        self.label_8.setObjectName("label_8")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_4.setGeometry(QtCore.QRect(20, 180, 113, 28))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_9 = QtWidgets.QLabel(self.frame_3)
        self.label_9.setGeometry(QtCore.QRect(20, 160, 261, 16))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.frame_3)
        self.label_10.setGeometry(QtCore.QRect(20, 210, 271, 16))
        self.label_10.setObjectName("label_10")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_5.setGeometry(QtCore.QRect(20, 230, 113, 28))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.label_11 = QtWidgets.QLabel(self.frame_3)
        self.label_11.setGeometry(QtCore.QRect(20, 260, 281, 16))
        self.label_11.setObjectName("label_11")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_6.setGeometry(QtCore.QRect(20, 280, 113, 28))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_7.setGeometry(QtCore.QRect(20, 330, 113, 28))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.label_12 = QtWidgets.QLabel(self.frame_3)
        self.label_12.setGeometry(QtCore.QRect(20, 310, 281, 16))
        self.label_12.setObjectName("label_12")
        self.label_19 = QtWidgets.QLabel(self.frame_3)
        self.label_19.setGeometry(QtCore.QRect(230, 10, 111, 31))
        self.label_19.setObjectName("label_19")
        self.frame_5 = QtWidgets.QFrame(Dialog)
        self.frame_5.setGeometry(QtCore.QRect(10, 500, 211, 181))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_2.setGeometry(QtCore.QRect(70, 140, 81, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton = QtWidgets.QPushButton(self.frame_5)
        self.pushButton.setGeometry(QtCore.QRect(20, 50, 171, 28))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_3.setGeometry(QtCore.QRect(40, 90, 131, 28))
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_18 = QtWidgets.QLabel(self.frame_5)
        self.label_18.setGeometry(QtCore.QRect(20, 10, 181, 31))
        self.label_18.setObjectName("label_18")
        self.frame_6 = QtWidgets.QFrame(Dialog)
        self.frame_6.setGeometry(QtCore.QRect(560, 280, 511, 201))
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.label_13 = QtWidgets.QLabel(self.frame_6)
        self.label_13.setGeometry(QtCore.QRect(20, 10, 261, 16))
        self.label_13.setObjectName("label_13")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.frame_6)
        self.textBrowser_2.setGeometry(QtCore.QRect(20, 40, 471, 141))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.frame_7 = QtWidgets.QFrame(Dialog)
        self.frame_7.setGeometry(QtCore.QRect(580, 130, 121, 141))
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.label_16 = QtWidgets.QLabel(self.frame_7)
        self.label_16.setGeometry(QtCore.QRect(10, 10, 81, 31))
        self.label_16.setObjectName("label_16")
        self.radioButton = QtWidgets.QRadioButton(self.frame_7)
        self.radioButton.setGeometry(QtCore.QRect(10, 60, 104, 21))
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.frame_7)
        self.radioButton_2.setGeometry(QtCore.QRect(10, 100, 104, 21))
        self.radioButton_2.setObjectName("radioButton_2")
        self.frame_8 = QtWidgets.QFrame(Dialog)
        self.frame_8.setGeometry(QtCore.QRect(250, 500, 821, 181))
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.checkBox = QtWidgets.QCheckBox(self.frame_8)
        self.checkBox.setGeometry(QtCore.QRect(20, 40, 801, 31))
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(self.frame_8)
        self.checkBox_2.setGeometry(QtCore.QRect(20, 70, 791, 21))
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_3 = QtWidgets.QCheckBox(self.frame_8)
        self.checkBox_3.setGeometry(QtCore.QRect(20, 110, 791, 21))
        self.checkBox_3.setObjectName("checkBox_3")
        self.checkBox_4 = QtWidgets.QCheckBox(self.frame_8)
        self.checkBox_4.setGeometry(QtCore.QRect(20, 90, 781, 21))
        self.checkBox_4.setObjectName("checkBox_4")
        self.label_17 = QtWidgets.QLabel(self.frame_8)
        self.label_17.setGeometry(QtCore.QRect(160, 0, 371, 31))
        self.label_17.setObjectName("label_17")
        self.checkBox_5 = QtWidgets.QCheckBox(self.frame_8)
        self.checkBox_5.setGeometry(QtCore.QRect(20, 130, 791, 21))
        self.checkBox_5.setObjectName("checkBox_5")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(140, 10, 791, 91))
        self.label_7.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label_7.setObjectName("label_7")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(20, 10, 211, 91))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("droid.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(860, 10, 211, 91))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("maxdemon.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.frame_4 = QtWidgets.QFrame(Dialog)
        self.frame_4.setGeometry(QtCore.QRect(720, 130, 351, 141))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.textBrowser = QtWidgets.QTextBrowser(self.frame_4)
        self.textBrowser.setGeometry(QtCore.QRect(20, 50, 261, 71))
        self.textBrowser.setObjectName("textBrowser")
        self.label_20 = QtWidgets.QLabel(self.frame_4)
        self.label_20.setGeometry(QtCore.QRect(20, 20, 261, 16))
        self.label_20.setObjectName("label_20")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600;\">query protein file list</span></p></body></html>"))
        self.label_14.setText(_translate("Dialog", "<html><head/><body><p>i.e. bound or mutant</p></body></html>"))
        self.label_15.setText(_translate("Dialog", "<html><head/><body><p>i.e.unbound or wildtype</p></body></html>"))
        self.label_2.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-weight:600;\">reference protein file list</span></p></body></html>"))
        self.label_5.setText(_translate("Dialog", "<html><head/><body><p>number of subsamples</p></body></html>"))
        self.label_6.setText(_translate("Dialog", "<html><head/><body><p>frames iper subsample (e.g. 100)</p></body></html>"))
        self.label_8.setText(_translate("Dialog", "<html><head/><body><p>total number of frames</p></body></html>"))
        self.label_9.setText(_translate("Dialog", "<html><head/><body><p>number of protein chains</p></body></html>"))
        self.label_10.setText(_translate("Dialog", "<html><head/><body><p>number of AA sites in protein</p></body></html>"))
        self.label_11.setText(_translate("Dialog", "<html><head/><body><p>start number on N terminus (e.g. 1)</p></body></html>"))
        self.label_12.setText(_translate("Dialog", "<html><head/><body><p>chimerax path /usr/lib/ucsf-chimerax/bin/</p></body></html>"))
        self.label_19.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">inputs</span></p></body></html>"))
        self.pushButton_2.setText(_translate("Dialog", "exit"))
        self.pushButton.setText(_translate("Dialog", "run MD parsing"))
        self.pushButton_3.setText(_translate("Dialog", "run analyses"))
        self.label_18.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">program control</span></p></body></html>"))
        self.label_13.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-weight:600;\">more information</span></p></body></html>"))
        self.textBrowser_2.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">BabbittLab at RIT</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">https://people.rit.edu/gabsbi/</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">citations</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:100%; background-color:transparent;\"><span style=\" font-family:\'Open Sans, serif\'; font-size:11pt;\">Babbitt G.A.</span><span style=\" font-family:\'Open Sans, serif\'; font-size:11pt; font-style:italic;\"> Coppola E.E</span><span style=\" font-family:\'Open Sans, serif\'; font-size:11pt;\">. </span><span style=\" font-family:\'Open Sans, serif\'; font-size:11pt; font-style:italic;\">Mortensen J.S.</span><span style=\" font-family:\'Open Sans, serif\'; font-size:11pt;\"> </span><span style=\" font-family:\'Open Sans, serif\'; font-size:11pt; font-style:italic;\">Adams L.E. Liao J. K.</span><span style=\" font-family:\'Open Sans, serif\'; font-size:11pt;\"> 2018. DROIDS 1.2 – a GUI-based pipeline for GPU-accelerated comparative protein dynamics. BIOPHYSICAL JOURNAL 114: 1009-1017. CELL Press.</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:100%; background-color:transparent;\"><span style=\" font-family:\'Open Sans, serif\'; font-size:11pt;\">Babbitt G.A.</span><span style=\" font-family:\'Open Sans, serif\'; font-size:11pt; font-style:italic;\"> </span><span style=\" font-family:\'Open Sans, serif\'; font-size:11pt;\">Fokoue E.</span><span style=\" font-family:\'Open Sans, serif\'; font-size:11pt; font-style:italic;\"> Evans J.R. Diller K.I. Adams L.E. </span><span style=\" font-family:\'Open Sans, serif\'; font-size:11pt;\">2020. DROIDS 3.0 - Detection of genetic and drug class variant impact on conserved protein binding dynamics. BIOPHYSICAL JOURNAL 118: 541-551 CELL Press.</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:100%; background-color:transparent;\"><span style=\" font-family:\'Open Sans, serif\'; font-size:11pt;\">Babbitt G.A. Fokoue E.P. </span><span style=\" font-family:\'Open Sans, serif\'; font-size:11pt; font-style:italic;\">Srivastava H.R. Callahan B. Rajendran M</span><span style=\" font-family:\'Open Sans, serif\'; font-size:11pt;\">. 2022.</span><span style=\" font-family:\'ArialUnicodeMS, serif\'; font-size:14pt; color:#333666;\"> </span><span style=\" font-family:\'Open Sans, serif\'; font-size:11pt;\">Statistical machine learning for comparative protein dynamics with the DROIDS/maxDemon software pipeline. STAR PROTOCOLS 3(1):101194</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_16.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">graphs</span></p></body></html>"))
        self.radioButton.setText(_translate("Dialog", "light"))
        self.radioButton_2.setText(_translate("Dialog", "dark"))
        self.checkBox.setText(_translate("Dialog", "site-wise comparison with divergence metrics (KL relative entropy in aton fluctuation)"))
        self.checkBox_2.setText(_translate("Dialog", "site-wise comparison of learned  features (kernel processes on local fluctuation and correlation)"))
        self.checkBox_3.setText(_translate("Dialog", "site-wise identification of conserved molecular dynamics via resampled learning classification"))
        self.checkBox_4.setText(_translate("Dialog", "site-wise identification of coordinated dynamics via mutual information on learned classification"))
        self.label_17.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">machine learning analyses to be run</span></p></body></html>"))
        self.checkBox_5.setText(_translate("Dialog", "site-wise comparison of genetic and/or drug class variants with divergence metrics"))
        self.label_7.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; color:#ffffff;\">DROIDS/maxDemon 5.0 </span></p><p align=\"center\"><span style=\" font-size:16pt; color:#ffffff;\">AI-assisted Comparative Molecular Dynamics</span></p></body></html>"))
        self.textBrowser.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">/path2file/1cdw_bound.pdb</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">/path2file/1cdw_bound.prmtop</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">/path2file/1cdw_bound.nc</p></body></html>"))
        self.label_20.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-weight:600;\">file list example </span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
